- hosts: controller
  tasks:
    - name: install validation script
      copy: src=openstack-validate dest=/usr/local/bin/openstack-validate
            mode="0755"
    - file: path=/root/keystonerc_demo state=file
    - name: verify that openstack is minimally functional
      command: /usr/local/bin/openstack-validate /root/keystonerc_demo
