- hosts: controller
  tasks:
    - name: verify that keystone is functioning
      shell: ". /root/keystonerc_admin; keystone user-list"
    - name: verify that glance is functioning (1)
      shell: ". /root/keystonerc_admin; glance image-list"
    - name: verify that glance is functioning (2)
      shell: ". /root/keystonerc_admin; glance image-download cirros > /dev/null"
    - name: verify that cinder is functioning
      shell: ". /root/keystonerc_admin; cinder list"
    - name: verify that neutron is functioning
      shell: ". /root/keystonerc_admin; neutron net-list"
    - name: verify that nova is functioning
      shell: ". /root/keystonerc_admin; nova list"

