#!/bin/bash

[ "$1" ] && . $1

get_status () {
	nova show $1 | awk '$2 == "status" {print $4}'
}

res=0
name="validate-$(openssl rand -hex 8)"
if nova boot --image cirros --flavor m1.tiny $name; then
	let tries=0
	while :; do
		status=$(get_status $name)

		case $status in
		(ACTIVE)
			break
			;;
		(ERROR)
			echo "boot failed"
			res=1
			break
			;;
		esac
	
		let tries++
		if [[ $tries -gt 12 ]]; then
			echo "boot failed"
			res=1
			break
		fi
		echo "waiting for $name to boot"
		sleep 5
	done

	if [[ $res -eq 0 ]]; then
		if nova delete $name; then
			let tries=0
			while nova show $name > /dev/null 2>&1; do
				let tries++
				if [[ $tries -gt 4 ]]; then
					echo "delete failed"
					res=1
					break
				fi
				echo "waiting for $name to delete"
				sleep 5
			done
		else
			echo "delete failed"
			res=1
		fi
	fi
else
	echo "boot failed"
	res=1
fi

exit $res

